--!strict

local Replicated = game:GetService("ReplicatedStorage")
local Battle = Replicated.Events.GUIBattleStart
local cam = game.Workspace.CurrentCamera
local char = game.Players.LocalPlayer.Character
local chitbox = game.Workspace.Creatures.Chitbox

Replicated = game:GetService("ReplicatedStorage")
local Battle = Replicated.Events.GUIBattleStart
local cam = game.Workspace.CurrentCamera
local char = game.Players.LocalPlayer.Character
local chitbox = game.Workspace.Creatures.Chitbox

