--!strict

wait(2)
local Replicated = game:GetService("ReplicatedStorage")
local module = require(Replicated.ProtoInfo)
local maxHealth = module.Floracri.Health

print(maxHealth)
currentHealth.Value = maxHealth)
local Replicated = game:GetService("ReplicatedStorage")
local module = require(Replicated.ProtoInfo)
local maxHealth = module.Floracri.Health

print(maxHealth)
currentHealth.Value = maxHealth