--[[
    Description.
]]

------ Services (Full Name)
-- local TweenService = game:GetService("TweenService")
-- local ServerStorage = game:GetService("ServerStorage")
-- local ServerStorage = game:GetService("ServerStorage")

------ Requires (Keep Name of File)
-- local Abilities = require(ServerStorage.Modules.Protomains.Species.Abilities)

------ Constants
-- local CONSTANT = 5

------ Init Module Table (or function)
local Module = {}

------ Add stuff to Module

------ Return Module Table
return Module
